# Generated by Django 5.0 on 2023-12-12 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0002_maildeliverysettings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maildeliverysettings',
            options={'verbose_name': 'Рассылка', 'verbose_name_plural': 'Рассылки'},
        ),
        migrations.AddField(
            model_name='maildeliverysettings',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Название рассылки'),
        ),
    ]
